#
# This workflow will plan and apply changes to the ${{ vars.DEFAULT_ENVIRONMENT }} automatically on push to the
# given branch.
#

name: Terraform CI/CD

run-name: Deployment to '${{ vars.DEFAULT_ENVIRONMENT }}' based on branch '${{ github.event_name }}'

on:
  push:
    branches:
      # set to the default branch
      - 'main'

permissions:
  id-token: write
  contents: write
  pull-requests: write

jobs:
  terraform:
    uses: Schumann-IT/terraform-gh-workflows/.github/workflows/terraform.yaml@main
    secrets: inherit
    with:
      environment: ${{ vars.DEFAULT_ENVIRONMENT }}
      mode: apply
