#
# This workflow will plan changes for all environments automatically on pull request changes
#
# NOTE: To deploy changes, you can use the workflow_dispatch workflow with using run-id of a run
#       triggered by this workflow as an input.
#

name: Terraform CI/CD

run-name: Plan for all environments based on PR '${{ github.event.pull_request.title }}'

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

permissions:
  id-token: write
  contents: write
  pull-requests: write

jobs:
  terraform:
    uses: Schumann-IT/terraform-gh-workflows/.github/workflows/terraform.yaml@main
    secrets: inherit
    with:
      environment: all
      mode: plan
