#
# This workflow will only validate the terraform code on push to any branch and on pull requests
#

name: Terraform CI

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

  push:
    branches:
      - '*'

permissions:
  id-token: write
  contents: write
  pull-requests: write

jobs:
  terraform:
    uses: Schumann-IT/terraform-gh-workflows/.github/workflows/terraform.yaml@main
    secrets: inherit
